# Generated by Django 5.2.8 on 2026-02-20 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowerapp', '0005_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='flower',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
