# Generated by Django 5.2.8 on 2026-02-26 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowerapp', '0010_order_idempotency_key_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='flower',
            name='light_requirement',
            field=models.CharField(default='Bright Indirect', max_length=50),
        ),
        migrations.AddField(
            model_name='flower',
            name='temperature',
            field=models.CharField(default='18–30°C', max_length=50),
        ),
        migrations.AddField(
            model_name='flower',
            name='water_frequency',
            field=models.CharField(default='Weekly', max_length=50),
        ),
    ]
