# Generated by Django 5.2.8 on 2026-02-28 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowerapp', '0013_customer_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='light_requirement',
            field=models.CharField(default='Bright Indirect', max_length=150),
        ),
        migrations.AlterField(
            model_name='flower',
            name='temperature',
            field=models.CharField(default='18–30°C', max_length=70),
        ),
        migrations.AlterField(
            model_name='flower',
            name='water_frequency',
            field=models.CharField(default='Weekly', max_length=80),
        ),
    ]
