# Generated by Django 5.2.8 on 2026-09-30 09:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowerapp', '0015_fcmtoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['pincode'], name='customer_pincode_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['phone_number'], name='customer_phone_idx'),
        ),
        migrations.AddIndex(
            model_name='flower',
            index=models.Index(fields=['price'], name='flower_price_idx'),
        ),
        migrations.AddIndex(
            model_name='flower',
            index=models.Index(fields=['stock'], name='flower_stock_idx'),
        ),
        migrations.AddIndex(
            model_name='flower',
            index=models.Index(fields=['name'], name='flower_name_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='order_status_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_status'], name='order_payment_status_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['-created_at'], name='order_created_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['total_amount'], name='order_amount_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['razorpay_order_id'], name='order_razorpay_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['idempotency_key'], name='order_idempotency_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', '-created_at'], name='order_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer', '-created_at'], name='order_customer_date_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['role'], name='profile_role_idx'),
        ),
    ]
